## 直接构造法
### torch.Tensor
通过函数torch.Tensor可以生成一个默认32位浮点数的Tensor
相关的函数有
1. torch.FloatTensor
2. torch.DoubleTensor
3. torch.ByteTensor
4. torch.ShortTensor
5. torch.IntTensor
6. torch.LongTensor

In [24]:
import torch
a = torch.Tensor(2,4)
print(a)
b = torch.Tensor([[1,3,5,7],[2,4,6,8]])
print(b)
c = torch.Tensor()
print(c)
d = torch.IntTensor([[1,2,3,4],[5,6,7,8]])
print(d)

tensor([[1.1857, 0.2526, 0.2047, 0.7831],
        [0.0541, 0.5034, 0.0279, 0.6951]])
tensor([[1., 3., 5., 7.],
        [2., 4., 6., 8.]])
tensor([])
tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]], dtype=torch.int32)


### torch.zeros
通过torch.zeros()返回一个Tensor，该Tensor维度给定且元素为0

In [25]:
a = torch.zeros(2,4)
print(a)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])


### torch.rand
通过函数torch.rand返回一个Tensor，该Tensor包含从区间[0,1)均匀分布中抽取的一组给定维度的随机数。

In [26]:
a = torch.rand(2,4)
print(a)

tensor([[0.3644, 0.7550, 0.7565, 0.5147],
        [0.3264, 0.0635, 0.9220, 0.3137]])


### torch.randn
通过函数torch.randn返回一个Tensor，包含从均值为0，方差为1的正太分布中抽取的一组给定维度的随机数。

In [27]:
a = torch.randn(2,4)
print(a)

tensor([[-0.2235,  0.4229,  0.4341,  0.1661],
        [ 1.3947, -1.3803,  0.9958,  1.8589]])


通过函数生成的Tensor可以像Numpy一样通过索引的方式获取其中的元素，也可以改变他的值

In [28]:
d[1,1]=40
print(d)

tensor([[ 1,  2,  3,  4],
        [ 5, 40,  7,  8]], dtype=torch.int32)


## 间接转换法
通过Pytorch提供的numpy.ndarray与Tensor之间内部转换函数来构造所需求的Tensor
torch.from_numpy()将Numpy数据转化为Tensor数据，
torch.nump()可以将Tensor数据转化为Numpy数据。

In [29]:
import numpy as np
a = np.ones((2,3),dtype = np.float32)
print(a)
b = torch.from_numpy(a)#a,b共享内存
a[1,1] = 10
print(a)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[ 1.  1.  1.]
 [ 1. 10.  1.]]
tensor([[ 1.,  1.,  1.],
        [ 1., 10.,  1.]])


## Tensor的转换
## Tensor类型的转换
可以在Tensor后面加上数据类型的方式，来改变Tensor的数据类型。

In [30]:
print(b.dtype)
b = b.int()
print(b)

torch.float32
tensor([[ 1,  1,  1],
        [ 1, 10,  1]], dtype=torch.int32)
